// <auto-generated />
using System;
using AccountingApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingApi.Data.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260304062738_AddPayDept")]
    partial class AddPayDept
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AccountingApi.Models.FSAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<string>("AcctDesc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_desc");

                    b.Property<string>("AcctType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurCredit")
                        .HasColumnType("TEXT")
                        .HasColumnName("cur_credit");

                    b.Property<decimal>("CurDebit")
                        .HasColumnType("TEXT")
                        .HasColumnName("cur_debit");

                    b.Property<decimal>("EndBal")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_bal");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("formula");

                    b.Property<string>("GlEffect")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("gl_effect");

                    b.Property<string>("GlReport")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("gl_report");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_code");

                    b.Property<bool>("Initialize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initialize");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<decimal>("OpenBal")
                        .HasColumnType("TEXT")
                        .HasColumnName("open_bal");

                    b.Property<string>("Schedule")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule");

                    b.Property<string>("SubGroup")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_group");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AcctCode")
                        .IsUnique();

                    b.ToTable("fs_accounts");
                });

            modelBuilder.Entity("AccountingApi.Models.FSAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JDOrC")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_d_or_c")
                        .HasAnnotation("Relational:JsonPropertyName", "jDOrC");

                    b.Property<DateTime>("JDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_date");

                    b.Property<string>("JJvNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_jv_no");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JJvNo");

                    b.ToTable("fs_adjstmnt");
                });

            modelBuilder.Entity("AccountingApi.Models.FSCashRcpt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JDOrC")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_d_or_c")
                        .HasAnnotation("Relational:JsonPropertyName", "jDOrC");

                    b.Property<DateTime>("JDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_date");

                    b.Property<string>("JJvNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_jv_no");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JJvNo");

                    b.ToTable("fs_cashrcpt");
                });

            modelBuilder.Entity("AccountingApi.Models.FSCheckMas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bank_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JCkNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_no");

                    b.Property<DateTime>("JDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_date");

                    b.Property<string>("JDesc")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_desc");

                    b.Property<string>("JJvNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_jv_no");

                    b.Property<string>("JPayTo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_pay_to");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<int>("SupNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sup_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JCkNo");

                    b.ToTable("fs_checkmas");
                });

            modelBuilder.Entity("AccountingApi.Models.FSCheckVou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JCkNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_no");

                    b.Property<string>("JDOrC")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_d_or_c")
                        .HasAnnotation("Relational:JsonPropertyName", "jDOrC");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JCkNo", "AcctCode");

                    b.ToTable("fs_checkvou");
                });

            modelBuilder.Entity("AccountingApi.Models.FSEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlEffect")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("gl_effect");

                    b.Property<string>("GlHead")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("gl_head");

                    b.Property<string>("GlReport")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("gl_report");

                    b.HasKey("Id");

                    b.HasIndex("GlReport", "GlEffect");

                    b.ToTable("fs_effects");
                });

            modelBuilder.Entity("AccountingApi.Models.FSJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JDOrC")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_d_or_c")
                        .HasAnnotation("Relational:JsonPropertyName", "jDOrC");

                    b.Property<DateTime>("JDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_date");

                    b.Property<string>("JJvNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_jv_no");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JJvNo");

                    b.ToTable("fs_journals");
                });

            modelBuilder.Entity("AccountingApi.Models.FSPostedJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JDOrC")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_d_or_c")
                        .HasAnnotation("Relational:JsonPropertyName", "jDOrC");

                    b.Property<DateTime?>("JDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_date");

                    b.Property<string>("JJvNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_jv_no");

                    b.HasKey("Id");

                    b.HasIndex("JJvNo", "AcctCode");

                    b.ToTable("fs_pournals");
                });

            modelBuilder.Entity("AccountingApi.Models.FSPurcBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JDOrC")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_d_or_c")
                        .HasAnnotation("Relational:JsonPropertyName", "jDOrC");

                    b.Property<DateTime>("JDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_date");

                    b.Property<string>("JJvNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_jv_no");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JJvNo");

                    b.ToTable("fs_purcbook");
                });

            modelBuilder.Entity("AccountingApi.Models.FSSaleBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("JCkAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_ck_amt");

                    b.Property<string>("JDOrC")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_d_or_c")
                        .HasAnnotation("Relational:JsonPropertyName", "jDOrC");

                    b.Property<DateTime>("JDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("j_date");

                    b.Property<string>("JJvNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("j_jv_no");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JJvNo");

                    b.ToTable("fs_salebook");
                });

            modelBuilder.Entity("AccountingApi.Models.FSScheduleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_code");

                    b.Property<string>("AcctDesc")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("acct_desc");

                    b.Property<string>("GlHead")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("gl_head");

                    b.HasKey("Id");

                    b.HasIndex("GlHead", "AcctCode");

                    b.ToTable("fs_schedule");
                });

            modelBuilder.Entity("AccountingApi.Models.FSSysId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BegDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("beg_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<int>("PresMo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pres_mo");

                    b.Property<int>("PresYr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pres_yr");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("fs_sys_id");
                });

            modelBuilder.Entity("AccountingApi.Models.PayDept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bontax")
                        .HasColumnType("TEXT")
                        .HasColumnName("bontax");

                    b.Property<decimal>("Bontot")
                        .HasColumnType("TEXT")
                        .HasColumnName("bontot");

                    b.Property<decimal>("CalLoan")
                        .HasColumnType("TEXT")
                        .HasColumnName("cal_loan");

                    b.Property<decimal>("Commodloan")
                        .HasColumnType("TEXT")
                        .HasColumnName("commodloan");

                    b.Property<decimal>("CompLoan")
                        .HasColumnType("TEXT")
                        .HasColumnName("comp_loan");

                    b.Property<string>("DepNm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_nm");

                    b.Property<string>("DepNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_no");

                    b.Property<decimal>("EcEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("ec_er");

                    b.Property<int>("EmpCtr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("emp_ctr");

                    b.Property<decimal>("GrsPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("grs_pay");

                    b.Property<decimal>("HolPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("hol_pay");

                    b.Property<decimal>("LsencPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("lsenc_pay");

                    b.Property<decimal>("LvencPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("lvenc_pay");

                    b.Property<decimal>("MedEe")
                        .HasColumnType("TEXT")
                        .HasColumnName("med_ee");

                    b.Property<decimal>("MedEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("med_er");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("net_pay");

                    b.Property<decimal>("OtPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("ot_pay");

                    b.Property<decimal>("OthDed1")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded1");

                    b.Property<decimal>("OthDed10")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded10");

                    b.Property<decimal>("OthDed2")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded2");

                    b.Property<decimal>("OthDed3")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded3");

                    b.Property<decimal>("OthDed4")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded4");

                    b.Property<decimal>("OthDed5")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded5");

                    b.Property<decimal>("OthDed6")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded6");

                    b.Property<decimal>("OthDed7")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded7");

                    b.Property<decimal>("OthDed8")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded8");

                    b.Property<decimal>("OthDed9")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded9");

                    b.Property<decimal>("OthPay1")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_pay1");

                    b.Property<decimal>("OthPay2")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_pay2");

                    b.Property<decimal>("OthPay3")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_pay3");

                    b.Property<decimal>("PbgLoan")
                        .HasColumnType("TEXT")
                        .HasColumnName("pbg_loan");

                    b.Property<decimal>("PgbgEe")
                        .HasColumnType("TEXT")
                        .HasColumnName("pgbg_ee");

                    b.Property<decimal>("PgbgEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("pgbg_er");

                    b.Property<decimal>("RegPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_pay");

                    b.Property<decimal>("SssEe")
                        .HasColumnType("TEXT")
                        .HasColumnName("sss_ee");

                    b.Property<decimal>("SssEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("sss_er");

                    b.Property<decimal>("SssLoan")
                        .HasColumnType("TEXT")
                        .HasColumnName("sss_loan");

                    b.Property<decimal>("Tax")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepNo")
                        .IsUnique();

                    b.ToTable("pay_dept");
                });

            modelBuilder.Entity("AccountingApi.Models.PayMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<decimal>("BRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("b_rate");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birthdate");

                    b.Property<decimal>("CalAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cal_amt");

                    b.Property<decimal>("CalBal")
                        .HasColumnType("TEXT")
                        .HasColumnName("cal_bal");

                    b.Property<DateTime?>("CalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cal_date");

                    b.Property<int>("CalTerm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cal_term");

                    b.Property<decimal>("Cola")
                        .HasColumnType("TEXT")
                        .HasColumnName("cola");

                    b.Property<decimal>("ComdAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("comd_amt");

                    b.Property<decimal>("ComdBal")
                        .HasColumnType("TEXT")
                        .HasColumnName("comd_bal");

                    b.Property<DateTime?>("ComdDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("comd_date");

                    b.Property<int>("ComdTerm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comd_term");

                    b.Property<decimal>("CompAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("comp_amt");

                    b.Property<decimal>("CompBal")
                        .HasColumnType("TEXT")
                        .HasColumnName("comp_bal");

                    b.Property<DateTime?>("CompDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("comp_date");

                    b.Property<int>("CompTerm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comp_term");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateHire")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_hire");

                    b.Property<DateTime?>("DateResign")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_resign");

                    b.Property<string>("DepNo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_no");

                    b.Property<string>("EmpNm")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("emp_nm");

                    b.Property<string>("EmpNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("emp_no");

                    b.Property<string>("EmpStat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("emp_stat");

                    b.Property<decimal>("HdmfAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("hdmf_amt");

                    b.Property<decimal>("HdmfBal")
                        .HasColumnType("TEXT")
                        .HasColumnName("hdmf_bal");

                    b.Property<DateTime?>("HdmfDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("hdmf_date");

                    b.Property<int>("HdmfTerm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hdmf_term");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<decimal>("MBasic")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_basic");

                    b.Property<decimal>("MCola")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_cola");

                    b.Property<decimal>("MEcer")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_ecer");

                    b.Property<decimal>("MGross")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_gross");

                    b.Property<decimal>("MHol")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_hol");

                    b.Property<decimal>("MLeave")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_leave");

                    b.Property<decimal>("MMedee")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_medee");

                    b.Property<decimal>("MMeder")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_meder");

                    b.Property<decimal>("MNetpay")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_netpay");

                    b.Property<decimal>("MOt")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_ot");

                    b.Property<decimal>("MOthp1")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_othp1");

                    b.Property<decimal>("MOthp2")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_othp2");

                    b.Property<decimal>("MOthp3")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_othp3");

                    b.Property<decimal>("MOthp4")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_othp4");

                    b.Property<decimal>("MPgee")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_pgee");

                    b.Property<decimal>("MPger")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_pger");

                    b.Property<decimal>("MSsee")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_ssee");

                    b.Property<decimal>("MSser")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_sser");

                    b.Property<decimal>("MTax")
                        .HasColumnType("TEXT")
                        .HasColumnName("m_tax");

                    b.Property<bool>("Pgbg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pgbg");

                    b.Property<string>("PgbgNo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("pgbg_no");

                    b.Property<string>("PhicNo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("phic_no");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<decimal>("Q1Gross")
                        .HasColumnType("TEXT")
                        .HasColumnName("q1_gross");

                    b.Property<decimal>("Q1Medee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q1_medee");

                    b.Property<decimal>("Q1Pgee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q1_pgee");

                    b.Property<decimal>("Q1Ssee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q1_ssee");

                    b.Property<decimal>("Q1Tax")
                        .HasColumnType("TEXT")
                        .HasColumnName("q1_tax");

                    b.Property<decimal>("Q2Gross")
                        .HasColumnType("TEXT")
                        .HasColumnName("q2_gross");

                    b.Property<decimal>("Q2Medee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q2_medee");

                    b.Property<decimal>("Q2Pgee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q2_pgee");

                    b.Property<decimal>("Q2Ssee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q2_ssee");

                    b.Property<decimal>("Q2Tax")
                        .HasColumnType("TEXT")
                        .HasColumnName("q2_tax");

                    b.Property<decimal>("Q3Gross")
                        .HasColumnType("TEXT")
                        .HasColumnName("q3_gross");

                    b.Property<decimal>("Q3Medee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q3_medee");

                    b.Property<decimal>("Q3Pgee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q3_pgee");

                    b.Property<decimal>("Q3Ssee")
                        .HasColumnType("TEXT")
                        .HasColumnName("q3_ssee");

                    b.Property<decimal>("Q3Tax")
                        .HasColumnType("TEXT")
                        .HasColumnName("q3_tax");

                    b.Property<decimal>("SickLeave")
                        .HasColumnType("TEXT")
                        .HasColumnName("sick_leave");

                    b.Property<decimal>("SlnAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sln_amt");

                    b.Property<decimal>("SlnBal")
                        .HasColumnType("TEXT")
                        .HasColumnName("sln_bal");

                    b.Property<DateTime?>("SlnDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("sln_date");

                    b.Property<int>("SlnTerm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sln_term");

                    b.Property<string>("Spouse")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("spouse");

                    b.Property<bool>("SssMember")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sss_member");

                    b.Property<string>("SssNo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("sss_no");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TinNo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tin_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VacationLeave")
                        .HasColumnType("TEXT")
                        .HasColumnName("vacation_leave");

                    b.Property<decimal>("YBasic")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_basic");

                    b.Property<decimal>("YBonus")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_bonus");

                    b.Property<decimal>("YBtax")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_btax");

                    b.Property<decimal>("YCola")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_cola");

                    b.Property<decimal>("YEcer")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_ecer");

                    b.Property<decimal>("YGross")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_gross");

                    b.Property<decimal>("YHol")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_hol");

                    b.Property<decimal>("YLeave")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_leave");

                    b.Property<decimal>("YMedee")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_medee");

                    b.Property<decimal>("YMeder")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_meder");

                    b.Property<decimal>("YNetpay")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_netpay");

                    b.Property<decimal>("YOt")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_ot");

                    b.Property<decimal>("YOthp1")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_othp1");

                    b.Property<decimal>("YOthp2")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_othp2");

                    b.Property<decimal>("YOthp3")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_othp3");

                    b.Property<decimal>("YOthp4")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_othp4");

                    b.Property<decimal>("YPgee")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_pgee");

                    b.Property<decimal>("YPger")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_pger");

                    b.Property<decimal>("YSsee")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_ssee");

                    b.Property<decimal>("YSser")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_sser");

                    b.Property<decimal>("YTax")
                        .HasColumnType("TEXT")
                        .HasColumnName("y_tax");

                    b.HasKey("Id");

                    b.HasIndex("EmpNo")
                        .IsUnique();

                    b.ToTable("pay_master");
                });

            modelBuilder.Entity("AccountingApi.Models.PayPremPaid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("month");

                    b.Property<DateTime?>("OrDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("or_date");

                    b.Property<string>("OrSbr")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("or_sbr");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("period");

                    b.Property<string>("PreFlag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("preflag");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("pay_prempaid");
                });

            modelBuilder.Entity("AccountingApi.Models.PaySysId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BegDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("beg_date");

                    b.Property<int>("BonDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bon_days");

                    b.Property<decimal>("BonMont")
                        .HasColumnType("TEXT")
                        .HasColumnName("bon_mont");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<decimal>("HdmfPre")
                        .HasColumnType("TEXT")
                        .HasColumnName("hdmf_pre");

                    b.Property<bool>("MDailyWage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("m_daily_wage");

                    b.Property<bool>("NeedBackup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("need_backup");

                    b.Property<int>("PayType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pay_type");

                    b.Property<decimal>("PgHigher")
                        .HasColumnType("TEXT")
                        .HasColumnName("pg_higher");

                    b.Property<decimal>("PgHiper")
                        .HasColumnType("TEXT")
                        .HasColumnName("pg_hiper");

                    b.Property<decimal>("PgLower")
                        .HasColumnType("TEXT")
                        .HasColumnName("pg_lower");

                    b.Property<decimal>("PgLwper")
                        .HasColumnType("TEXT")
                        .HasColumnName("pg_lwper");

                    b.Property<int>("PresMo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pres_mo");

                    b.Property<int>("PresYr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pres_yr");

                    b.Property<decimal>("TaxBon")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_bon");

                    b.Property<int>("TrnCtr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_ctr");

                    b.Property<int>("TrnPrc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_prc");

                    b.Property<int>("TrnUpd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_upd");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_hours");

                    b.HasKey("Id");

                    b.ToTable("pay_sys_id");
                });

            modelBuilder.Entity("AccountingApi.Models.PayTaxTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Exemption")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("exemption");

                    b.Property<decimal>("Percent")
                        .HasColumnType("TEXT")
                        .HasColumnName("percent");

                    b.Property<decimal>("Peso")
                        .HasColumnType("TEXT")
                        .HasColumnName("peso");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT")
                        .HasColumnName("salary");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("Exemption", "Sequence");

                    b.ToTable("pay_taxtab");
                });

            modelBuilder.Entity("AccountingApi.Models.PayTmcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AbsDed")
                        .HasColumnType("TEXT")
                        .HasColumnName("abs_ded");

                    b.Property<decimal>("AbsHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("abs_hrs");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT")
                        .HasColumnName("bonus");

                    b.Property<decimal>("Bonustax")
                        .HasColumnType("TEXT")
                        .HasColumnName("bonustax");

                    b.Property<decimal>("CalDed")
                        .HasColumnType("TEXT")
                        .HasColumnName("cal_ded");

                    b.Property<decimal>("ComdDed")
                        .HasColumnType("TEXT")
                        .HasColumnName("comd_ded");

                    b.Property<decimal>("CompDed")
                        .HasColumnType("TEXT")
                        .HasColumnName("comp_ded");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DepNo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_no");

                    b.Property<decimal>("EcEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("ec_er");

                    b.Property<string>("EmpNm")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("emp_nm");

                    b.Property<string>("EmpNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("emp_no");

                    b.Property<decimal>("GrsPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("grs_pay");

                    b.Property<decimal>("HdmfDed")
                        .HasColumnType("TEXT")
                        .HasColumnName("hdmf_ded");

                    b.Property<string>("LegacyRowHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_row_hash");

                    b.Property<decimal>("LghpHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("lghp_hrs");

                    b.Property<decimal>("LghpPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("lghp_pay");

                    b.Property<decimal>("LgotHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("lgot_hrs");

                    b.Property<decimal>("LgotPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("lgot_pay");

                    b.Property<decimal>("LsCashout")
                        .HasColumnType("TEXT")
                        .HasColumnName("ls_cashout");

                    b.Property<decimal>("LsHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("ls_hrs");

                    b.Property<decimal>("LsPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("ls_pay");

                    b.Property<decimal>("Lv2Pay")
                        .HasColumnType("TEXT")
                        .HasColumnName("lv2_pay");

                    b.Property<decimal>("LvCashout")
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_cashout");

                    b.Property<decimal>("LvHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_hrs");

                    b.Property<decimal>("LvPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_pay");

                    b.Property<decimal>("MedEe")
                        .HasColumnType("TEXT")
                        .HasColumnName("med_ee");

                    b.Property<decimal>("MedEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("med_er");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("net_pay");

                    b.Property<decimal>("NsdHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("nsd_hrs");

                    b.Property<decimal>("NsdPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("nsd_pay");

                    b.Property<decimal>("OthDed1")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded1");

                    b.Property<decimal>("OthDed10")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded10");

                    b.Property<decimal>("OthDed2")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded2");

                    b.Property<decimal>("OthDed3")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded3");

                    b.Property<decimal>("OthDed4")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded4");

                    b.Property<decimal>("OthDed5")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded5");

                    b.Property<decimal>("OthDed6")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded6");

                    b.Property<decimal>("OthDed7")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded7");

                    b.Property<decimal>("OthDed8")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded8");

                    b.Property<decimal>("OthDed9")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_ded9");

                    b.Property<decimal>("OthPay1")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_pay1");

                    b.Property<decimal>("OthPay2")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_pay2");

                    b.Property<decimal>("OthPay3")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_pay3");

                    b.Property<decimal>("OthPay4")
                        .HasColumnType("TEXT")
                        .HasColumnName("oth_pay4");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("period_month");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("period_year");

                    b.Property<decimal>("PgbgEe")
                        .HasColumnType("TEXT")
                        .HasColumnName("pgbg_ee");

                    b.Property<decimal>("PgbgEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("pgbg_er");

                    b.Property<decimal>("RegHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_hrs");

                    b.Property<decimal>("RegPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("reg_pay");

                    b.Property<decimal>("RotHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("rot_hrs");

                    b.Property<decimal>("RotPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("rot_pay");

                    b.Property<decimal>("SlnDed")
                        .HasColumnType("TEXT")
                        .HasColumnName("sln_ded");

                    b.Property<decimal>("SphpHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("sphp_hrs");

                    b.Property<decimal>("SphpPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("sphp_pay");

                    b.Property<decimal>("SpotHrs")
                        .HasColumnType("TEXT")
                        .HasColumnName("spot_hrs");

                    b.Property<decimal>("SpotPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("spot_pay");

                    b.Property<decimal>("SssEe")
                        .HasColumnType("TEXT")
                        .HasColumnName("sss_ee");

                    b.Property<decimal>("SssEr")
                        .HasColumnType("TEXT")
                        .HasColumnName("sss_er");

                    b.Property<decimal>("TaxAdd")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_add");

                    b.Property<decimal>("TaxEe")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_ee");

                    b.Property<decimal>("TotDed")
                        .HasColumnType("TEXT")
                        .HasColumnName("tot_ded");

                    b.Property<string>("TrnFlag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("trn_flag");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Withbonus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("withbonus");

                    b.HasKey("Id");

                    b.HasIndex("TrnFlag");

                    b.HasIndex("EmpNo", "PeriodYear", "PeriodMonth");

                    b.ToTable("pay_tmcard");
                });
#pragma warning restore 612, 618
        }
    }
}
